import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
                <Link href="/board">
                    <a className="text-2xl font-semibold text-slate-50 hover:underline">GRAJ</a>
                </Link>
            </main>
        </>
    );
};

export default Home;
